### ISSUE TITLE
Speaking - Modify speaking front-end pages

### ISSUE THREAD

**Issue by sahmedkh** [bahrain-uob/gen-ai-moe-challenge#129]
The front-end code is non-understandable, it needs major refactoring. Moreover, the continuous microphone recording needs to be fixed ASAP. Furthermore, we should have an indicator on the response expectation.

**Comment by mzhubail** [comment]
@mzhubail I'll have to pick this up I suppose.

**Comment by mzhubail** [comment]
See #155.
