### ISSUE TITLE
General - Storing feedback in database

### ISSUE THREAD

**Issue by Ma-hawaj** [bahrain-uob/gen-ai-moe-challenge#135]
- Modifying the question retrieval function to store the question in the database 
- See how the feedback will be structured in the database.

**Comment by mzhubail** [comment]
From what I see this is closely related to how the full test is implemented and sections exams (in case of full test, we'll just gather the feedbacks in one place).  Is there something I'm missing?

**Comment by Ma-hawaj** [comment]
You're right

**Comment by mzhubail** [comment]
@Ma-hawaj Update me on the status of this.

I think you already have a PR for this with feedback error handling too.

**Comment by Ma-hawaj** [comment]
Yes
