### ISSUE TITLE
Frontend - Implement Full Test

### ISSUE THREAD

**Issue by mzhubail** [bahrain-uob/gen-ai-moe-challenge#149]
I'm thinking of using websockets to manage simulating the full test experience.

- Handle storing student's progress
- Handle the timing in the backend (that way the timing cannot be modified in the interface)

**Comment by mzhubail** [comment]
Since we'll be dealing with time.  I suggest using [ISO 8601](http://en.wikipedia.org/wiki/ISO_8601), this format is well supported and widely use.

Regarding dealing with dates, we can use the built-in `Date` object, but sometimes it has its own limitations.  One framework/library I suggest is [date-fns](https://date-fns.org/).  (recommended by [Ionic](https://ionicframework.com/) project.)

Research both options and pick the one you see fit @Ma-hawaj.

**Comment by Ma-hawaj** [comment]
Seems like the dates-fn library uses the same built-in Date object so in terms of backend we can just use the Date and in the frontend we could use the dates-fn library based on how we want to display the date.
Am I right?

**Comment by mzhubail** [comment]
> Seems like the dates-fn library uses the same built-in Date object so in terms of backend we can just use the Date and in the frontend we could use the dates-fn library based on how we want to display the date. Am I right?

I didn't look into how it works behind the hood.  The main point of using a library is to make stuff easier that you would otherwise have to implement yourself.  In addition, sometimes there are edge cases relevant to some time zones or whatever.  It might be just easier to have a well-tested, consistent API.

If you're more comfortable with native `Date`, there's no issue in using it.

I'll probably use `date-fns` in the front-end.

**Comment by mzhubail** [comment]
This issue is dragging on for too long.

Most of the full test front end work was done by Wednesday, May 22nd.

Work started in #203, where initial start test and get question functionalities where implemented.  By that time only listening page was integrated, still with hard coded urls, but getting questions from the back-end.

In #215, the full test experience matured a bit, now with submit functionality, and with the reading page integrated. Dummy pages for writing and speaking where added too.  Moreover a dummy page was added between sections.  The front-end now covers most of the possible inputs from the back-end.

In #226, user experience was enhanced a bit by adding a loading spinner.  Added a working countdown timer to force submit.

Finally, #229 saw many functionality improvements, including integrating writing page, adding auto-save, and taking in saved answers from the back-end.  Countdown timer's inner workings were improved; albeit, the timing is wrong (using url time, instead of time sent from the back-end).  Another thing to note, is that the writing page is using a different structure than that used by the back-end (which made me do some gymnastics to convert between formats).

All in all, there is much remaining work for (A) making a combined feedback page, (B) proper type sharing between the back-end and front-end, preferably using `packages/core`, but we'll look into that later, (C) perhaps improving the pages design (Al-doseri has rightly commented on the lack of bolds in our interface), and (D) adding some sort of runtime data checking as to avoid cryptic errors.

Those mentioned points will be explored in other issues, where appropriate.
