### ISSUE TITLE
Backend - Implement Full Test

### ISSUE THREAD

**Issue by Ma-hawaj** [bahrain-uob/gen-ai-moe-challenge#174]

**Comment by mzhubail** [comment]
Below is an overview of the life of your typical full mock test.  Note that the middle part of the sequence was removed because it's just repetitive.

![Architecture diagram - MOE-SM - github](https://github.com/bahrain-uob/gen-ai-moe-challenge/assets/143425328/815fba6a-5e63-42ff-a42d-47da6292897a)

**Comment by mzhubail** [comment]
@Ma-hawaj good job on this
