### ISSUE TITLE
Store the Grade of the section test to use it for the plan

### ISSUE THREAD

**Issue by Ma-hawaj** [bahrain-uob/gen-ai-moe-challenge#243]

**Comment by mzhubail** [comment]
@Ma-hawaj update us on the status of this

**Comment by Ma-hawaj** [comment]
Actually I forgot about that but it have been done to implement another feature.
So, yes it is done.

**Comment by Ma-hawaj** [comment]
But what we need now is the updating of the plan based on the grade which may need a pop up to ask about updating the plan.

**Comment by mzhubail** [comment]
@Ma-hawaj add it in the planner for now, so we don't forget about it.
