### ISSUE TITLE
Reading- create the question retriever lambda

### ISSUE THREAD

**Issue by DanaK270** [bahrain-uob/gen-ai-moe-challenge#43]
must create the DB first

**Comment by cerashdan** [comment]
This is a server-side error (500 - internal server error) which means the error is probably in the AWS Lambda function receiving that request. 

Open the cloudwatch logs for your function, read it through and paste it here so we can better understand this error.

**Comment by cerashdan** [comment]
You can expand the error messages also from your browser to see what is the error, this will give you and us more clues on what could be the issue. @DanaK270

**Comment by DanaK270** [comment]
cloud watch log:
![Image](https://github.com/bahrain-uob/gen-ai-moe-challenge/assets/137807775/14af26d3-7005-45aa-9c24-b6d5fba38476)

browser:



![Image](https://github.com/bahrain-uob/gen-ai-moe-challenge/assets/137807775/647b3e7b-a9df-4ebf-90fe-3440497f0f07)



when i click on the initiator link:


![Image](https://github.com/bahrain-uob/gen-ai-moe-challenge/assets/137807775/9efbbaef-6f58-4246-a53a-20d9b4e0ccd7)


@cerashdan

**Comment by DanaK270** [comment]
fixed the issue. I deleted a function but forgot to delete one of its calls. I deleted the call now and the site started working again. Thanks for your help @cerashdan
