### ISSUE TITLE
General - Implement Authentication

### ISSUE THREAD

**Issue by mzhubail** [bahrain-uob/gen-ai-moe-challenge#51]
Implement authentication. (preferably using Cognito, I guess.)

**Comment by mzhubail** [comment]
Regarding the customer's remarks about active directory.  I did some research and found that this can be added later with minimum effort.

For now we'll be using regular cognito user pool, and later we can change `AuthStack` to add MOE active directory as a SAML identity provider (and the rest of the application need not be changed, except for sign-in page).

See: https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-saml-idp.html
"... through a SAML identity provider (IdP) like Microsoft Active Directory Federation Services (ADFS) ..."

@maramesk

**Comment by maramesk** [comment]
Great job diving deep @mzhubail, go ahead with the cognito user pool for now. @cerashdan if you could give Moh read only access onto the UniRoute repo for him to reference their cognito code since I dont have admin access to do so.

**Comment by cerashdan** [comment]
I added @mzhubail to the repository

**Comment by mzhubail** [comment]
Noted @maramesk.

I did follow [one of the sst examples](https://sst.dev/examples/how-to-add-jwt-authorization-with-cognito-user-pool-to-a-serverless-api.html) and implemented authentication with `jwt`.

For now
- I have working sign up, sign in, sign out
- All api routes by default are private (available only for logged in users), unless the api endpoint is made public explicitly.

Note that for sign in, I **removed email verification**.  I did this because it will make it easier for us to create users during development, and because email verification is not relevant to our requirements.

If you have any comments please do let me know.

**Comment by mzhubail** [comment]
Note that I installed `Amplify` to handle authentication in the front-end.

- See [this](https://docs.amplify.aws/react/build-a-backend/auth/enable-sign-up/) for more information on the available operations.
- If you want to call an API see `TestPage` for an example, or see [this](https://docs.amplify.aws/react/build-a-backend/restapi/fetch-data/) and [this](https://docs.amplify.aws/react/build-a-backend/restapi/update-data/) for more.

**Comment by mzhubail** [comment]
### Note on calling APIs.

Please read @xvbilalvx @Farhalsada @saraisa12 @sahmedkh @Ma-hawaj @ErasedKyte @ThatIsHero @DanaK270 

If you get error `unauthorized`, try changing your code.  Instead of using `fetch` you should use api calls provided by `Amplify`.  See the following example.

```ts
import { toJSON } from '../utilities';      // Use this if your lambda returns json
import { post } from 'aws-amplify/api';     // This is the API call from `Amplify`
...

const response = await toJSON(
  post({
    apiName: 'myAPI',       // Don't change this
    path: '/writing',
    options: {
      // Optional request headers
      headers: {
        Accept: 'application/json',
        'Content-Type': 'application/json',
      },
      // Optional request body
      body: {
        inputs,
      },
    },
  }),
);

setGrading(response);       // response contains the json object returned from `/writing`
```


Note that you don't need to use `import.meta.env.VITE_API_URL`, this is handled by `Amplify`.

If you need any help, please do reach out to me.

**Comment by mzhubail** [comment]
### Another note on calling APIs

If you want to call an API you can use try-catch to handle errors (e.g. Bad Request, Internal Server Error).

Below is an example of how to do it.

```ts
import { ApiError, get } from 'aws-amplify/api';

try {
  const restOperation = get({ 
    apiName: 'todo-api',
    path: '/todo' 
  });
  await restOperation.response;
} catch (error) {
  if (error instanceof ApiError) {
    if (error.response) {
      const { 
        statusCode, 
        headers, 
        body 
      } = error.response;
      console.error(`Received ${statusCode} error response with payload: ${body}`);
    }
    // Handle API errors not caused by HTTP response.
  }
  // Handle other errors.
}
```

**You don't have to do this, but if you get a weird `Amplify` error, this is the reason.**

The above code was taken from [here](https://docs.amplify.aws/javascript/build-a-backend/restapi/fetch-data/#accessing-response-payload).

@xvbilalvx @Farhalsada @saraisa12 @sahmedkh @Ma-hawaj @ErasedKyte @ThatIsHero @DanaK270
