### ISSUE TITLE
General - adding the institution attribute to the sign up process

### ISSUE THREAD

**Issue by Ma-hawaj** [bahrain-uob/gen-ai-moe-challenge#84]
* Add a custom attribute (institution)

* Add a post sign up lambda that add the student ID to the institution students index and initialize the aggregates for the user in the database

**Comment by mzhubail** [comment]
Custom attribute was added in #75.  Adding info to database is remaining.

**Comment by mzhubail** [comment]
@Ma-hawaj Please create a draft pull request.
